version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: illuminate/translation
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: respect/validation
    versions:
    - 2.1.0
    - 2.2.1
    - 2.2.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: jblond/php-diff
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
